name: Push Github

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build files
      run: |
        yarn
        yarn docs:build
    - name: Commit files
      run: |
        git config --local user.email "519052532@qq.com"
        git config --local user.name "SoulLyoko"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        directory: docs/.vuepress/dist
        repository: soullyoko.github.io
        github_token: ${{ secrets.GITHUB_TOKEN }}